"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
Do Not Move on to the next function until its tests report 'ok' or your code
may not work as expected.
"""

import unittest
from test_createIndex import TestCreateIndex
from test_recordBook import TestRecordBook
from test_findBook import TestFindBook
from test_listBooks import TestListBooks
from test_formatMenu import TestFormatMenu
from test_formatMenuPrompt import TestFormatMenuPrompt
from test_getUserChoice import TestGetUserChoice
from test_getISBN import TestGetISBN
from test_getTitle import TestGetTitle
from test_recordBookAction import TestRecordBookAction
from test_findBookAction import TestFindBookAction
from test_listBooksAction import TestListBooksAction
from test_quitAction import TestQuitAction
from test_applyAction import TestApplyAction

if __name__ == '__main__':
    testCases = [
        TestCreateIndex,
        TestRecordBook,
        TestFindBook,
        TestListBooks,
        TestFormatMenu,
        TestFormatMenuPrompt,
        TestGetUserChoice,
        TestGetISBN,
        TestGetTitle,
        TestRecordBookAction,
        TestFindBookAction,
        TestListBooksAction,
        TestQuitAction,
        TestApplyAction,
    ]

    allTests = [ ]
    for testCase in testCases:
        allTests.append( unittest.TestLoader( ).loadTestsFromTestCase( testCase ) )

    unittest.TextTestRunner( ).run( unittest.TestSuite( allTests ) )
