"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import sys
if sys.version_info.major != 3:
    print('You must use Python 3.x version to run this unit test')
    sys.exit(1)

import unittest
import unittest.mock

import main

class TestApplyAction(unittest.TestCase):
    def input_replacement(self, prompt):
        self.assertFalse(self.too_many_inputs)
        self.input_given_prompt = prompt
        r = self.input_response_list[self.input_response_index]
        self.input_response_index += 1
        if self.input_response_index >= len(self.input_response_list):
            self.input_response_index = 0
            self.too_many_inputs = True
        return r

    def print_replacement(self, *text, **kwargs):
        line = " ".join(text) + "\n"
        self.printed_lines.append(line)

    def setUp(self):
        self.too_many_inputs = False
        self.input_given_prompt = None
        self.input_response_index = 0
        self.input_response_list = [""]
        main.input = self.input_replacement

        self.printed_lines = []
        main.print = self.print_replacement

        self.exit_called = False
        self.exit_value = -1

    def tearDown(self):
        main.input = input
        main.print = print

    def test001_applyActionExists(self):
        self.assertTrue('applyAction' in dir(main),
                        'Function "applyAction" is not defined, check your spelling')

    def assert_called(self, f, msg=""):
        try:
            f.assert_called()
        except AssertionError:
            self.fail(msg)

    def assert_not_called(self, f, msg=""):
        try:
            f.assert_not_called()
        except AssertionError:
            self.fail(msg)

    @unittest.mock.patch("main.quitAction")
    @unittest.mock.patch("main.recordActivityAction")
    @unittest.mock.patch("main.eatFoodAction")
    def test002_applyActionCallsEatFoodActivity(self, eatFoodAction,
            recordActivityAction, quitAction):
        from main import applyAction
        from caloric_balance import CaloricBalance
        cb = CaloricBalance('f', 23.0, 65.0, 130.0)
        obal = cb.getBalance()
        applyAction(cb, "f")
        self.assertEqual(obal, cb.getBalance(), 'applyAction should not change the caloric balance.')
        self.assert_called(eatFoodAction, "Option 'f' was provided, eatFoodAction should have been called.")
        self.assert_not_called(recordActivityAction, "Option 'f' was provided, recordActivityAction should not have been called.")
        self.assert_not_called(quitAction,  "Option 'f' was provided, quitAction should not have been called.")
        lines = "    ".join(self.printed_lines)
        self.assertEqual(len(self.printed_lines), 0,
                         'Nothing should be printed in the applyAction function.\n' +
                         'You printed:\n    %s' % lines
                         )

    @unittest.mock.patch("main.quitAction")
    @unittest.mock.patch("main.recordActivityAction")
    @unittest.mock.patch("main.eatFoodAction")
    def test003_applyActionCallsRecordActivityAction(self, eatFoodAction,
            recordActivityAction, quitAction):
        from main import applyAction
        from caloric_balance import CaloricBalance
        cb = CaloricBalance('f', 23.0, 65.0, 130.0)
        obal = cb.getBalance()
        applyAction(cb, "a")
        self.assertEqual(obal, cb.getBalance(), 'applyAction should not change the caloric balance.')
        self.assert_not_called(eatFoodAction, "Option 'a' was provided, eatFoodAction should not have been called.")
        self.assert_called(recordActivityAction, "Option 'a' was provided, recordActivity should have been called.")
        self.assert_not_called(quitAction, "Option 'a' was provided, quitAction should not have been called.")
        lines = "    ".join(self.printed_lines)
        self.assertEqual(len(self.printed_lines), 0,
                         'Nothing should be printed in the applyAction function.\n' +
                         'You printed:\n    %s' % lines
                         )

    @unittest.mock.patch("main.quitAction")
    @unittest.mock.patch("main.recordActivityAction")
    @unittest.mock.patch("main.eatFoodAction")
    def test004_applyActionCallsQuitAction(self, eatFoodAction,
            recordActivityAction, quitAction):
        from main import applyAction
        from caloric_balance import CaloricBalance
        cb = CaloricBalance('f', 23.0, 65.0, 130.0)
        obal = cb.getBalance()
        applyAction(cb, "q")
        self.assertEqual(obal, cb.getBalance(), 'applyAction should not change the caloric balance.')
        self.assert_not_called(eatFoodAction, "Option 'a' was provided, eatFoodAction should not have been called.")
        self.assert_not_called(recordActivityAction, "Option 'a' was provided, recordActivity should have been called.")
        self.assert_called(quitAction, "Option 'a' was provided, quitAction should not have been called.")
        lines = "    ".join(self.printed_lines)
        self.assertEqual(len(self.printed_lines), 0,
                         'Nothing should be printed in the applyAction function.\n' +
                         'You printed:\n    %s' % lines
                         )

    @unittest.mock.patch("main.quitAction")
    @unittest.mock.patch("main.recordActivityAction")
    @unittest.mock.patch("main.eatFoodAction")
    def test005_applyActionDetectsIllegalAction(self, eatFoodAction,
            recordActivityAction, quitAction):
        from main import applyAction
        from caloric_balance import CaloricBalance
        cb = CaloricBalance('f', 23.0, 65.0, 130.0)
        obal = cb.getBalance()
        applyAction(cb, "x")
        self.assertEqual(obal, cb.getBalance(), 'applyAction should not change the caloric balance.')
        self.assert_not_called(eatFoodAction, "An illegal option was provided, eatFoodAction should not have been called.")
        self.assert_not_called(recordActivityAction, "An illegal option was provided, recordActivityAction should not have been called.")
        self.assert_not_called(quitAction, "An illegal option was provided, quitAction should not have been called.")
        lines = "    ".join(self.printed_lines)
        self.assertGreaterEqual(len(self.printed_lines), 1,
                         'You should have printed an error message to the user.\n' +
                         'You printed:\n    %s' % lines
                         )

    @unittest.mock.patch("main.quitAction")
    @unittest.mock.patch("main.recordActivityAction")
    @unittest.mock.patch("main.eatFoodAction")
    def test006_illegalAction_activityActions(self, eatFoodAction,
            recordActivityAction, quitAction):
        from main import formatActivityMenu
        from main import applyAction
        from caloric_balance import CaloricBalance
        import re

        menu = formatActivityMenu()
        options = []
        for line in menu:
            matches = re.findall("\[([a-z0-9]+)\]", line)
            if len(matches) > 0:
                options += matches

        self.assertGreaterEqual(len(options), 4, 'Have you finished formatActivityMenu?')

        for option in options:
            if option not in ['f', 'a', 'q']:
                self.setUp()
                cb = CaloricBalance('f', 23.0, 65.0, 130.0)
                obal = cb.getBalance()
                applyAction(cb, option)
                self.assertEqual(obal, cb.getBalance(), 'applyAction should not change the caloric balance.')
                self.assert_not_called(eatFoodAction,
                    "An illegal option (%s) was provided, eatFoodAction should not have been called." % option)
                self.assert_not_called(recordActivityAction,
                    "An illegal option (%s) was provided, recordActivityAction should not have been called." % option)
                self.assert_not_called(quitAction,
                    "An illegal option (%s) was provided, quitAction should not have been called." % option)
                lines = "".join(self.printed_lines)
                self.assertGreaterEqual(len(self.printed_lines), 1,
                                 'You should have printed an error message to the user.\n'+
                                 'Your printed lines were:\n%s' % lines
                                 )


if __name__ == '__main__':
    unittest.main()
